name: Deploy React to cPanel

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: npm run build

      - name: Check local dist folder size
        run: du -sh dist

      - name: Check server public_html folder size
        run: |
          sudo apt-get update
          sudo apt-get install -y lftp
          lftp -c "set ssl:verify-certificate no; open -u ${{ secrets.FTP_USERNAME }},${{ secrets.FTP_PASSWORD }} ftps://ftp.eaglines.co; du -sh public_html"

      - name: Deploy to cPanel
        uses: SamKirkland/FTP-Deploy-Action@v4.3.6
        with:
          server: ftp.eaglines.co
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: dist/
          server-dir: public_html/
          exclude: "*.map,*.log"
          dry-run: "false"